FROM nginx

VOLUME static
COPY . static
# COPY index.html /usr/share/nginx/html
# COPY index.html /usr/share/nginx/html
# COPY messages.html /usr/share/nginx/html
# COPY og.html /usr/share/nginx/html
# COPY profile.html /usr/share/nginx/html
# COPY signup.html /usr/share/nginx/html

# COPY . /usr/share/nginx/html
# COPY js /usr/share/nginx/html/
# COPY fonts /usr/share/nginx/html/
# COPY css /usr/share/nginx/html/
# COPY img /usr/share/nginx/html/
ADD default.conf /etc/nginx/conf.d/default.conf

